version: '3'
services:
  flask-oai-img:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development 
    networks:
      - backend
networks:
  backend:
    external:
      name: flaskapp